version: "3.8"
services:
  at-better-web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    environment:
      DATABASE_TYPE: sqlite
    ports:
      - "8000:8000"
    volumes:
      - ./stories:/stories