name: AskTable-Better

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Aliyun Docker Registry
      run: echo ${{ secrets.ALIYUN_DOCKER_REGISTRY_PASSWORD }} | docker login --username=${{ secrets.ALIYUN_DOCKER_REGISTRY_USER }} --password-stdin registry.cn-shanghai.aliyuncs.com

    - name: Build, tag and push Docker image
      uses: docker/build-push-action@v5.0.0
      with:
        context: .
        file: docker/Dockerfile
        push: true
        tags: |
          registry.cn-shanghai.aliyuncs.com/datamini/asktable-better:latest
        platforms: linux/amd64 # ,linux/arm64
        cache-from: type=gha # 启用 GitHub Actions 缓存，适用于跨工作流缓存
        cache-to: type=gha,mode=max # 启用缓存并优化构建

    - name: Execute deployment script  # 只更新、重启，不提供 docker-compose.yaml 文件
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.SERVER_HOST_SH4 }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASSWORD }}
        port: 22
        script: |
          # 进入部署目录
          cd /root/sh4/at-better/
          # 拉取最新镜像
          docker-compose pull && docker-compose down
          # 启动容器
          docker-compose up -d